# This file shall contain routes used to build URLs that we want to reference
# within the application, but are not part of the application. These routes
# fall into one of two buckets:
#
# 1) A url to an external product, e.g. iplayer, Sounds
# 2) A url to a /programmes page we have not yet migrated. As we migrate pages,
#    we shall move these routes into the main routes.yaml.
#
# All routes in this file shall be configured with
# defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
# This means that the url can be routed by this application but throws a 404.

### External Products

iplayer_play:
    path: /iplayer/episode/{pid}/{version}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '', version: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', version: 'hd|ad|sign' }
    schemes: [https]

iplayer_episodes:
    path: /iplayer/episodes/{pid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [https]

iplayer_live:
    path: /iplayer/live/{sid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { sid: '[0-9a-z_]{1,}' }
    schemes: [https]

worldservice_liveradio:
    host: "bbc.com"
    path: /{language}/{sid}/liveradio
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { language: '[a-z]{1,}', sid: '[0-9a-z_]{1,}' }
    schemes: [http]

worldservice_news_west_africa:
    path: /news/av/world-africa-29144792/bbc-world-service-africa

network:
    path: /{networkUrlKey}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { networkUrlKey: '[a-zA-Z0-9]{2,35}' }

playspace_live:
    path: /radio/play/live:{sid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { sid: '[0-9a-z_]{1,}' }

playspace_play:
    path: /radio/play/{pid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

music_artist:
    path: /music/artists/{mbid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { mbid: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' }

my_tracks:
    path: /music/tracks/my
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }

### /programmes v2

atoz_list_all:
    path: /programmes/a-z/all
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    schemes: [https]

categories_show:
    path: /programmes/{categoryType}/{urlKeyHierarchy}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { categoryType: 'formats|genres', urlKeyHierarchy: '.+' }
    schemes: [https]

programme_clips:
    path: /programmes/{pid}/clips
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [https]

article_with_contact_form:
    path: /programmes/articles/{key}/{slug}/contact
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { key: '[a-zA-Z0-9-]{1,40}' }
    schemes: [https]

programme_galleries:
    path: /programmes/{pid}/galleries
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [https]

programme_topics:
    path: /programmes/{pid}/topics
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [http]

programme_topics_topic:
    path: /programmes/{pid}/topics/{topic}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [http]

# TODO implement slice and filter parameters properly
programme_broadcasts:
    path: /programmes/{pid}/broadcasts
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [https]

topics:
    path: /programmes/topics
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    schemes: [http]

topics_topic:
    path: /programmes/topics/{topic}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    schemes: [http]

podcast_download:
    path: /mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/https/vpid/{pid}.mp3
    host: 'open.live.bbc.co.uk'
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    schemes: [https]

podcast_download_low:
    path: /mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download-low/proto/https/vpid/{pid}.mp3
    host: 'open.live.bbc.co.uk'
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    schemes: [https]

food_recipes:
    path: /food/programmes/{pid}
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: '' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
    schemes: [http]

